### ISSUE TITLE
Stunned card

### ISSUE THREAD

**Issue by Restland** [MOj0/LoR-Bot#13]
When one of my cards was stunned the bot was trying to play it till the round ran out of time.

**Comment by MOj0** [comment]
Yeah, this is a limitation, since it only knows the static data for each card (card_sets folder).
So this is more of a farm bot, not a bot to climb ranks with. In order to to that I would need to read values from the game's memory directly and form proper strategies, which would be fun to do sometime.

**Comment by Restland** [comment]
That's sad hopefully it will get there, Is there anything that changed since the last update? The bot seems to be very slow too. Like it plays when the timer shows up

**Comment by MOj0** [comment]
No, nothing is changed, except for the added card sets (you can check the commit history). I'm not sure why it would be slow all of a sudden. I guess it is having a hard time reading the mana values, but that worked fine as I remember, and I didn't change that...so I don't know.

**Comment by Restland** [comment]
Thanks!
