### ISSUE TITLE
Not functionning

### ISSUE THREAD

**Issue by ajdc2** [MOj0/LoR-Bot#27]
Hi, first of all thank you for making this.

I have trouble getting the bot to run past the select a deck part. I tried both in PVP and noPVP mode.

The bot selects the deck and launches the game just fine. But then I run into one of these issues (I don't know what causes the one or the other):

-Either the bot moves the cursor to the center of the screen when the mulligan screen appears, then stops doing anything. In the console it repeats "Unknown mana..." over and over.

-Or, the bot repeats the movements to select a deck and launch a game, even though the game has already been launched. In the console it repeats "Selecting deck..." over and over.

In any case I have not been able to go past the mulligan screen with the bot... Do you know what is going wrong ?

**Comment by ajdc2** [comment]
Btw I am playing with the correct screen resolution and the quality set to medium. It seems the error where the cursor repeats the movement sequence to select the deck and launch the game indefinitely is more frequent.

**Comment by MOj0** [comment]
Hmm... now the issue where it repeats `Selecting deck...` over and over is quite strange. The bot gets the state of the game directly from the API of the Legends of Runeterra itself and does not use any image recognition (at least for distinction between `In Menu` and `In Game` states). This API is called [here](https://github.com/MOj0/LoR-Bot/blob/master/APICaller.py#L7). 

I would suggest to check if you have third party endpoints enabled and set them to port 21337 (the 4th bullet point in the [prerequsite section](https://github.com/MOj0/LoR-Bot#prerequisites)).

If the issue still occurs I would ask you to go debug it and print the values of the `state machine` component while an active game (not the menus) is running. The values are set [here](https://github.com/MOj0/LoR-Bot/blob/master/LOR_Bot.py#L51-L53).

**Comment by ajdc2** [comment]
Thank you for replying so fast !

I have tried to close the game and re-open in. Since then I cannot reproduce the selecting deck issue, only the unknown mana one. I confirm that i have third party endpoints enabled with 21337. The screen resolution is the one required, and I have tried all graphic settings from low to ultra with no success. Is there something else I should consider ?

Also, could you explain how I can go to debug ? I'm really sorry, I am not very good at this...

**Comment by MOj0** [comment]
Sure. So I've only tested this on a 1080p monitor on fullscreen. If you have a monitor with a different resolution, you will have to run it in windowed mode (which won't work unfortunately, but can be fixed) or fullscreen on a smaller resolution, which I assume won't work either because the image will be stretched or somewhat skewed. If you have a monitor which does not have 1080p resolution, the best option is to run it in windowed and modify the code such that it takes the height of the window title bar into account, otherwise it will try to look for mana values in the wrong spot.

To debug it in VS Code at least, you need to set a breakpoint to a certain line in the code (F9) and then run in it debug mode (F5). You will then be able to see all the variables and their values at the point in the program. Let me know if you need any additional help.

**Comment by ajdc2** [comment]
Okay so I didn't quite manage to do it with the debug method because I can't get VS code to work. I usually run it either though terminal using :
`py path/lor_bot noPVP`
or simply by double clicking on the icon (then it goes into pvp mode).

So I tried to add a `print(state_machine)` at line 54 in LOR_bot.py since I figured that was the idea ? This is what I get : 
<img width="1398" alt="Capture d’écran 2023-06-23 à 14 44 28" src="https://github.com/MOj0/LoR-Bot/assets/113511834/df24830d-4c63-4d15-b917-2388d84c891e">


I struggled to take the screen because of the scrolling but basically after this I get like `unknown mana...` followed by 20 or so lines of the `State_Machine.State_Machine etc` line, repeating indefinitely. The 0x number doesn't change in the course of the game, but if I close the bot and restart it I get a different one. I still haven't been able to reproduce the "selecting deck" error.

Does this help in any way ? If not, are there any other values I can print() that would be helpful to you ? Worst case scenario I can try to install an actual program to run python like Spyder.

Also, could it be that I start the bot wrong ? What I do is I launch LoR, then alt tab to the folder with the bot or to the windows terminal to run lor_bot, then I wait for this window to pop : 

<img width="1396" alt="Capture d’écran 2023-06-23 à 14 47 16" src="https://github.com/MOj0/LoR-Bot/assets/113511834/5fc9fffb-2223-4fea-945d-1b946f777ed1">

And then I manually go back to the LoR window and wait for the bot to kick in. If I don't manually go back then the bot just moves and clicks on top of that black terminal window repeatedly. Am I doing this right ?

Sorry for being such a noob, thanks for your patience...

**Comment by MOj0** [comment]
Ah, don't worry about it :smile:.
Now that I saw that screenshot I think I know what the issue could be. Since you're using a laptop, you very have a 125% scaling. That messes with the screen recognition for some reason. The scale has to be at 100% on 1920x1080 full screen resolution.
Regarding your `print`, you're getting the memory address of where the state machine is in your RAM :) . When you use `print` you'll have to print the values of the objects, not the objects themselves (or I should implement some sort of `__to_string` or whatever Python uses to print it out nicely, by default it prints its memory address).
You don't need any external programs like Spyder. The bot is already running just fine.
And yeah, that is the expected way to run it, since bot does not know what window it is clicking on, it is simply clicking on the screen coordinates.

**Comment by ajdc2** [comment]
That was it ! It works now <3

Thank you so much !
