### ISSUE TITLE
if u have some error with passing, try mine

### ISSUE THREAD

**Issue by z41nl** [MOj0/LoR-Bot#44]
i use old labtop like 7 year old one to run bot(may have problem with screen resolution), idk why the screen detects mana and all other smoothly but doesnt clicks "pass" button well, so i made as clicking "spacebar" to pass. i may edit clicking x and y axis but its better to just press spacebar.

original code : https://github.com/ziminl/LoR-Bot/blob/master/Bot.py#L135
edited one : https://github.com/ziminl/LoR-Bot/blob/master/Bot.py#L152

**Comment by MOj0** [comment]
Yeah passing of turns is not implemented intentionally. This is because it is hard to tell when to actually pass. If you implemented passing, what will happen is, for example, bot will cast a burst speed spell and it will think his turn is over and pass. There are also other such cases, where it could play more cards but will pass instead.
The solution is to enable auto passing in game.
