### ISSUE TITLE
keyerrors

### ISSUE THREAD

**Issue by ERROREND** [MOj0/LoR-Bot#6]
Several keyerrors, I believe due to new cards in game.

**Comment by MOj0** [comment]
I see. Normally this should be handled, but Riot apparently just updated the existing sets on their [website](https://developer.riotgames.com/docs/lor) instead of adding a new one. This is [fixed](https://github.com/MOj0/LoR-Bot/commit/cb0eb46696f0aab7ff5668048a1082f104902a41) now.
**Workaround for future reference:** In case you get a key error, you can simply delete the `card_sets` folder, and it will download them automatically (although it will take a while).
