### ISSUE TITLE
Cant make it run

### ISSUE THREAD

**Issue by Gran177** [MOj0/LoR-Bot#7]
![image](https://user-images.githubusercontent.com/110046240/181042247-71877ea7-6cba-4531-acd8-bdb4969e882c.png)

First of all, i dont know anything about python, managed to get the requirements.txt working after a few tries and now im stuck. What im doing wrong? thank you so much!!

**Comment by Gran177** [comment]
![image](https://user-images.githubusercontent.com/110046240/181042633-bd8757e9-67c1-4806-a526-5e4125a9f680.png)

tried with visual studio too

**Comment by MOj0** [comment]
Hi! I just updated the requirements, it seems there were some issues there (commit [here](https://github.com/MOj0/LoR-Bot/commit/384cd8e9c301b99566b9209598486d75eaabd61f)).
You can now pull the changes: `git pull origin master` and install the requirements: `pip install -r requirements.txt` and it should work. If it does you can close the issue, otherwise feel free to post further comments.
Also for the future, if you get a *No module named 'requests'* error, you can just do: `pip install requests` (or whatever the module name is :).

**Comment by Gran177** [comment]
worked perfectly! thanks!!!! really nice bot
