### ISSUE TITLE
 reconnecting button in game

### ISSUE THREAD

**Issue by ERROREND** [MOj0/LoR-Bot#9]
![image](https://user-images.githubusercontent.com/19989840/181723823-6554a466-ac69-4b4c-814c-d9ecc93c0055.png)
When reconnecting button is shown in game, it cannot continue.

**Comment by MOj0** [comment]
Hmm, I just tested this and once the game reconnected back, the bot worked just fine.
While the "Reconnecting..." screen is shown, the bot simply prints "Unknown mana..." and does nothing, which is the expected behaviour.
Also in general you can turn on the bot mid-game and it should work fine, so I don't know what the issue is here.

**Comment by ERROREND** [comment]
Yes, the issue is it wont press the quit button so that it will reconnect into the game / client interface. I think sometimes lag spikes /  freezes, can make the bot print "Unknown mana" and do nothing.  The only solution is restarting the bot and / or the client.

**Comment by MOj0** [comment]
So, if you just wait until you establish back the connection the game will resume and the bot will continue playing.
If the bot quit the game, it wouldn't know how to re-open it and that would be the issue. So I think the bot waiting for the connection is the expected behaviour.
